#!/bin/bash

# This file is part of Yandex Disk indicator and control (YDI).
# 
# Copyright 2025 Dandelion Systems <dandelion.systems@gmail.com>
# 
# YDI is free software; you can redistribute it and/or modify
# it under the terms of the MIT License.
# 
# YDI is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
# See the MIT License for more details.
# 
# SPDX-License-Identifier: MIT

#xgettext -d messages -o ../locales/messages.pot ../yd_appind.py --from-code UTF-8
#msginit -l en_US.UTF8 -o locales/en/LC_MESSAGES/messages.po -i locales/messages.pot --no-translator
#msginit -l ru_RU.UTF8 -o ../locales/ru/LC_MESSAGES/messages.po -i ../locales/messages.pot --no-translator
#msginit -l fr_FR.UTF8 -o locales/fr/LC_MESSAGES/messages.po -i locales/messages.pot --no-translator