#!/bin/bash

# This file is part of Yandex Disk indicator and control (YDI).
# 
# Copyright 2025 Dandelion Systems <dandelion.systems@gmail.com>
# 
# YDI is free software; you can redistribute it and/or modify
# it under the terms of the MIT License.
# 
# YDI is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
# See the MIT License for more details.
# 
# SPDX-License-Identifier: MIT

msgfmt -o ../locales/en/LC_MESSAGES/messages.mo ../locales/en/LC_MESSAGES/messages.po
msgfmt -o ../locales/ru/LC_MESSAGES/messages.mo ../locales/ru/LC_MESSAGES/messages.po
msgfmt -o ../locales/fr/LC_MESSAGES/messages.mo ../locales/fr/LC_MESSAGES/messages.po