#!/bin/bash

# This file is part of Yandex Disk indicator and control (YDI).
# 
# Copyright 2025 Dandelion Systems <dandelion.systems@gmail.com>
# 
# YDI is free software; you can redistribute it and/or modify
# it under the terms of the MIT License.
# 
# YDI is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
# See the MIT License for more details.
# 
# SPDX-License-Identifier: MIT

# Post removal script for deb package

set -u

(crontab -u $SUDO_USER -l | grep -v "dandelion.systems/ydi") | crontab -u $SUDO_USER -

THEHOME=$( getent passwd "$SUDO_USER" | cut -d: -f6 )

rm -Rf /opt/dandelion.systems/ydi/
rm -f $THEHOME/.config/autostart/dandelion.ydi.desktop
rm -f $THEHOME/.local/share/applications/dandelion.ydi.desktop

