#!/bin/bash

# This file is part of Yandex Disk indicator and control (YDI).
# 
# Copyright 2025 Dandelion Systems <dandelion.systems@gmail.com>
# 
# YDI is free software; you can redistribute it and/or modify
# it under the terms of the MIT License.
# 
# YDI is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
# See the MIT License for more details.
# 
# SPDX-License-Identifier: MIT

# Post installation script for deb package

set -u

# Register the "keep alive" script in crontab
NEW_CRON_ENTRY="0 * * * * /opt/dandelion.systems/ydi/yd_keep_alive.sh"
(crontab -u $SUDO_USER -l; echo "$NEW_CRON_ENTRY" ) | crontab -u $SUDO_USER -

# Configure autostart and lauchpad icon
THEHOME=$( getent passwd "$SUDO_USER" | cut -d: -f6 )

if [ ! -d $THEHOME/.config/autostart ]; then
	mkdir -p $THEHOME/.config/autostart
	chown $SUDO_USER:$SUDO_USER $THEHOME/.config/autostart
fi

mv /opt/dandelion.systems/ydi/dandelion.ydi.desktop $THEHOME/.config/autostart
chown $SUDO_USER:$SUDO_USER $THEHOME/.config/autostart/dandelion.ydi.desktop

cp $THEHOME/.config/autostart/dandelion.ydi.desktop $THEHOME/.local/share/applications
chown $SUDO_USER:$SUDO_USER $THEHOME/.local/share/applications/dandelion.ydi.desktop
